# Generated by Django 4.1.6 on 2024-05-11 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Board_News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('post_created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('post_updated_ad', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('type', models.CharField(choices=[('TANK', 'Танк'), ('HILL', 'Хилл'), ('DD', 'ДД'), ('MER', 'Торговец'), ('GILD', 'Гилдмастер'), ('KV', 'Квестгивер'), ('BS', 'Кузнец'), ('TAN', 'Кожевник'), ('ZE', 'Зельевар'), ('MI', 'Мастер заклинаний')], max_length=4, verbose_name='Категория')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='Изображение')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['post_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Описание')),
                ('comment_created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostComment', to='Board_News.post')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ['id'],
            },
        ),
    ]
